In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Training Dataset/training datalist.csv')
display(df.head())

ID  Sex  Age  Disease category  Narrow pitch range  Decreased volume  \
0  1202f15    2   39                 1                   1                 1   
1  0600ve0    1   69                 2                   1                 1   
2  1001o7l    2   59                 2                   1                 1   
3  1201c1t    2   47                 1                   1                 0   
4  0402jvt    1   87                 1                   0                 0   

   Fatigue  Dryness  Lumping  heartburn  ...  Onset of dysphonia   \
0        1        1        1          0  ...                    2   
1        1        1        0          0  ...                    2   
2        1        1        0          0  ...                    2   
3        1        1        1          0  ...                    3   
4        0        0        0          0  ...                    1   

   Noise at work  Occupational vocal demand  Diabetes  Hypertension  CAD  \
0              3                          1         0             0    0   
1              1                          3         0             0    0   
2              3                          4         0             0    0   
3              1                          1         0             0    0   
4              1                          4         0             1    0   

   Head and Neck Cancer  Head injury  CVA  Voice handicap index - 10  
0                     0            0    0                       22.0  
1                     0            0    1                       19.0  
2                     0            0    0                       18.0  
3                     0            0    0                       27.0  
4                     0            0    0                       16.0  

[5 rows x 28 columns]

In [3]:
# data cleaning
df['PPD'].fillna(0, inplace=True)
df.dropna(subset=['Voice handicap index - 10'], inplace=True)
# df.info()
df.reset_index(drop=True, inplace=True)

In [4]:
columns_to_drop = ['ID', 'Disease category', 'Diabetes', 'Hypertension', 'CAD', 'Head and Neck Cancer', 'Head injury', 'CVA', 'Onset of dysphonia ', 'Diurnal pattern']
# get certain columns as features
features = df.columns.drop(columns_to_drop).to_list()
print(features)

['Sex', 'Age', 'Narrow pitch range', 'Decreased volume', 'Fatigue', 'Dryness', 'Lumping', 'heartburn', 'Choking', 'Eye dryness', 'PND', 'Smoking', 'PPD', 'Drinking', 'frequency', 'Noise at work', 'Occupational vocal demand', 'Voice handicap index - 10']


In [5]:
from sklearn.model_selection import train_test_split

X = df.drop(['ID', 'Disease category'], axis=1)
# X = df[features]
y = df['Disease category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)


In [6]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train.values, y_train.values)

y_pred = forest.predict(X_test.values)

In [7]:
y_test.values

array([2, 1, 2, 1, 1, 2, 3, 1, 4, 1, 2, 2, 1, 2, 3, 3, 2, 1, 3, 5, 1, 1,
       1, 3, 3, 1, 2, 1, 2, 2, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2, 3,
       3, 1, 1, 1, 3, 4, 3, 3, 2, 1, 3, 2, 1, 1, 2, 1, 2, 1, 1, 2, 3, 1,
       1, 1, 1, 2, 1, 2, 2, 1, 1, 3, 2, 3, 1, 1, 3, 2, 2, 2, 3, 3, 1, 1,
       1, 5, 2, 1, 5, 4, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3,
       1, 2, 3, 3, 1, 2, 2, 5, 5, 1, 1, 3, 1, 3, 1, 3, 3, 1, 1, 3, 3, 1,
       3, 2, 1, 1, 3, 1, 1, 1, 1, 2, 2, 1, 1, 5, 1, 2, 1, 1, 2, 1, 1, 1,
       5, 1, 2, 1, 2, 1, 3, 3, 3, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 3, 1, 3,
       1, 5, 1, 3, 1, 1, 3, 3, 4, 1, 2, 1, 2, 1, 1, 1, 2, 4, 4, 2, 1, 1,
       3, 2, 3, 1, 1, 1, 3, 1, 1, 2, 1, 4, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1,
       1, 4, 1, 1, 3, 2, 5, 2, 1, 2, 1, 2, 3, 1, 1, 3, 2, 1, 1, 1, 1, 1,
       1, 1, 2, 3, 3, 5, 3, 1, 2, 3, 3, 2, 2, 1, 1, 2, 1, 4, 2, 1, 2, 2,
       2, 3, 3, 3, 1, 1, 1, 2, 3, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 3, 1, 4,
       1, 2, 5, 1, 1, 1, 3, 1, 3, 1, 3, 3])

In [8]:
y_pred

array([2, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 3, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 3, 1, 2, 1, 1, 2, 1, 1, 1, 1, 3, 1, 2, 1, 1, 2, 1, 2, 2, 3,
       3, 1, 1, 1, 3, 1, 1, 3, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 3, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 3, 1, 1, 3, 3, 2, 1, 2, 3, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 2, 3, 3, 1, 1, 1, 2, 1, 1, 1, 2, 4, 3, 1, 3, 2, 1, 1, 3, 3, 3,
       3, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 2, 1, 1, 1, 2,
       1, 1, 2, 3, 1, 1, 1, 3, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 1, 1, 1, 2, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 3, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1,
       3, 1, 1, 3, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2,
       1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 2, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 3, 1, 3, 2, 3, 3])

In [9]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test.values, y_pred)
f1 = f1_score(y_test.values, y_pred, average='weighted', zero_division=1)
precision = precision_score(y_test.values, y_pred, average='weighted', zero_division=1)
recall = recall_score(y_test.values, y_pred, average='weighted', zero_division=1)

print(f"Accuracy: {accuracy.round(2)}")
print(f"F1: {f1.round(2)}")
print(f"Precision: {precision.round(2)}")
print(f"Recall: {recall.round(2)}")

print(classification_report(y_test.values, y_pred, zero_division=1))
print(confusion_matrix(y_test.values, y_pred))

Accuracy: 0.65
F1: 0.62
Precision: 0.66
Recall: 0.65
              precision    recall  f1-score   support

           1       0.67      0.88      0.76       153
           2       0.52      0.44      0.47        64
           3       0.77      0.51      0.61        59
           4       0.50      0.09      0.15        11
           5       1.00      0.00      0.00        11

    accuracy                           0.65       298
   macro avg       0.69      0.38      0.40       298
weighted avg       0.66      0.65      0.62       298

[[135  11   6   1   0]
 [ 33  28   3   0   0]
 [ 17  12  30   0   0]
 [  8   2   0   1   0]
 [ 10   1   0   0   0]]


In [10]:
# print the error position
print("(test, pred)")
for i in range(len(y_test)):
    if y_test.values[i] != y_pred[i]:
        print((y_test.values[i], y_pred[i]))

(test, pred)
(2, 1)
(2, 1)
(3, 1)
(2, 1)
(2, 3)
(2, 1)
(3, 1)
(3, 1)
(5, 1)
(3, 1)
(2, 1)
(1, 2)
(1, 2)
(1, 2)
(4, 1)
(3, 1)
(1, 2)
(3, 1)
(2, 1)
(1, 2)
(2, 1)
(1, 2)
(2, 1)
(2, 1)
(2, 1)
(2, 1)
(2, 3)
(2, 1)
(3, 2)
(1, 2)
(5, 1)
(2, 1)
(5, 1)
(4, 1)
(4, 2)
(1, 3)
(2, 1)
(3, 2)
(2, 1)
(2, 1)
(5, 2)
(5, 1)
(3, 2)
(1, 4)
(3, 2)
(1, 3)
(2, 1)
(2, 1)
(5, 1)
(2, 1)
(5, 1)
(2, 1)
(3, 1)
(3, 1)
(1, 3)
(2, 1)
(3, 1)
(3, 2)
(5, 1)
(1, 2)
(3, 1)
(4, 1)
(2, 3)
(2, 1)
(4, 1)
(4, 1)
(3, 1)
(3, 2)
(3, 2)
(1, 3)
(2, 1)
(4, 2)
(3, 2)
(4, 1)
(5, 1)
(2, 1)
(3, 1)
(1, 2)
(3, 2)
(1, 3)
(2, 1)
(3, 1)
(5, 1)
(3, 2)
(3, 2)
(3, 1)
(2, 1)
(1, 2)
(4, 1)
(2, 1)
(2, 1)
(2, 1)
(3, 1)
(3, 1)
(2, 1)
(3, 1)
(2, 1)
(2, 1)
(1, 3)
(3, 2)
(4, 1)
(2, 1)
(5, 1)
(1, 2)


In [11]:
# plot tree
from sklearn import tree
import graphviz

# Select an individual decision tree from the Random Forest
selected_tree = forest.estimators_[0]

# Calculate the deppth of the selected decision tree
depth = selected_tree.get_depth()
print(depth)

# Plot the selected decision tree
dot_data = tree.export_graphviz(selected_tree, out_file=None,
                                feature_names=X_train.columns,
                                class_names=y_train.unique().astype(str),
                                filled=True, rounded=True,
                                special_characters=True)

graph = graphviz.Source(dot_data)
graph.render("random_forest_tree_full_data")  # Save the tree visualization as a file
graph.view()  # Display the tree visualization

18


'random_forest_tree_full_data.pdf'