In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
df = pd.read_csv('Training Dataset/training datalist.csv')
display(df.head())
df.reset_index(drop=True, inplace=True)

ID  Sex  Age  Disease category  Narrow pitch range  Decreased volume  \
0  1202f15    2   39                 1                   1                 1   
1  0600ve0    1   69                 2                   1                 1   
2  1001o7l    2   59                 2                   1                 1   
3  1201c1t    2   47                 1                   1                 0   
4  0402jvt    1   87                 1                   0                 0   

   Fatigue  Dryness  Lumping  heartburn  ...  Onset of dysphonia   \
0        1        1        1          0  ...                    2   
1        1        1        0          0  ...                    2   
2        1        1        0          0  ...                    2   
3        1        1        1          0  ...                    3   
4        0        0        0          0  ...                    1   

   Noise at work  Occupational vocal demand  Diabetes  Hypertension  CAD  \
0              3                          1         0             0    0   
1              1                          3         0             0    0   
2              3                          4         0             0    0   
3              1                          1         0             0    0   
4              1                          4         0             1    0   

   Head and Neck Cancer  Head injury  CVA  Voice handicap index - 10  
0                     0            0    0                       22.0  
1                     0            0    1                       19.0  
2                     0            0    0                       18.0  
3                     0            0    0                       27.0  
4                     0            0    0                       16.0  

[5 rows x 28 columns]

In [23]:
# data cleaning
df['PPD'].fillna(0, inplace=True)
df.dropna(subset=['Voice handicap index - 10'], inplace=True)
# df.info()

In [24]:
columns_to_drop = ['ID', 'Disease category', 'Diabetes', 'Hypertension', 'CAD', 'Head and Neck Cancer', 'Head injury', 'CVA', 'Onset of dysphonia ', 'Diurnal pattern']
# get certain columns as features
features = df.columns.drop(columns_to_drop).to_list()
print(features)

['Sex', 'Age', 'Narrow pitch range', 'Decreased volume', 'Fatigue', 'Dryness', 'Lumping', 'heartburn', 'Choking', 'Eye dryness', 'PND', 'Smoking', 'PPD', 'Drinking', 'frequency', 'Noise at work', 'Occupational vocal demand', 'Voice handicap index - 10']


In [25]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df.drop(['ID', 'Disease category'], axis=1)
# X = df[features]
y = df['Disease category']

# split the data with label evenly distributed
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,stratify=y, random_state=101)

# Print the class distribution in the training set
unique_labels, counts = np.unique(y_train, return_counts=True)
for label, count in zip(unique_labels, counts):
    print(f"Label {label}: {count} samples")

scaler = StandardScaler().fit(X_train.values)
X_train_norm = scaler.transform(X_train.values)
X_test_norm = scaler.transform(X_test.values)

Label 1: 372 samples
Label 2: 153 samples
Label 3: 117 samples
Label 4: 31 samples
Label 5: 22 samples


In [26]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(multi_class="multinomial", solver='lbfgs')
lr_model.fit(X_train_norm, y_train.values)

y_pred = lr_model.predict(X_test_norm)

In [27]:
y_test.values

array([3, 1, 2, 1, 1, 3, 3, 2, 2, 1, 1, 2, 3, 3, 1, 3, 2, 1, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 3, 4, 1, 1, 5, 1, 1, 1, 1, 1, 1, 2, 2, 5, 1, 1, 1,
       3, 4, 3, 4, 1, 2, 1, 3, 1, 1, 3, 3, 1, 5, 3, 1, 1, 1, 1, 3, 3, 3,
       1, 4, 2, 1, 1, 3, 3, 1, 1, 3, 2, 1, 1, 1, 1, 1, 2, 1, 3, 1, 3, 2,
       1, 2, 5, 1, 1, 1, 2, 5, 1, 1, 1, 1, 3, 1, 1, 2, 1, 2, 1, 1, 2, 1,
       1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 5, 1, 3, 2, 2, 2, 1, 1, 1, 1,
       1, 1, 3, 4, 1, 1, 1, 1, 1, 2, 1, 2, 1, 3, 1, 1, 2, 1, 1, 2, 4, 1,
       1, 2, 2, 3, 3, 2, 1, 1, 1, 5, 2, 1, 3, 3, 3, 3, 1, 3, 1, 1, 2, 4,
       3, 1, 2, 1, 1, 2, 3, 1, 3, 4, 1, 1, 2, 2, 2, 1, 1, 4, 1, 2, 5, 2,
       1, 1, 2, 1, 2, 3, 2, 1, 4, 1, 1, 2, 1, 5, 4, 1, 3, 1, 3, 1, 1, 1,
       2, 1, 2, 1, 2, 3, 1, 3, 2, 3, 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       3, 1, 4, 1, 1, 1, 3, 2, 5, 2, 1, 3, 1, 1, 2, 3, 1, 1, 1, 1, 1, 1,
       2, 2, 3, 1, 2, 3, 1, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 4, 1, 1, 2, 3,
       1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1])

In [28]:
y_pred

array([3, 1, 1, 1, 1, 3, 1, 3, 2, 1, 1, 3, 1, 3, 1, 2, 2, 1, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 3, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 5, 1, 1,
       3, 1, 1, 2, 2, 1, 1, 2, 1, 2, 3, 2, 1, 5, 3, 1, 1, 1, 1, 1, 2, 3,
       1, 2, 1, 1, 1, 3, 3, 1, 1, 3, 3, 1, 1, 1, 1, 2, 2, 1, 2, 1, 3, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1, 3, 1,
       2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 3, 1, 1, 1, 1,
       2, 1, 3, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 3, 1, 1, 2, 1, 1, 2, 1, 2,
       1, 2, 3, 3, 3, 1, 1, 2, 1, 1, 2, 2, 3, 4, 3, 3, 1, 2, 3, 1, 3, 3,
       1, 1, 3, 1, 1, 1, 3, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2,
       3, 1, 2, 1, 2, 1, 2, 1, 3, 1, 1, 3, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1,
       3, 1, 1, 5, 2, 3, 1, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       3, 1, 1, 1, 1, 1, 3, 3, 1, 2, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1,
       3, 1, 3, 1, 3, 2, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 3,
       3, 2, 1, 1, 1, 1, 3, 3, 1, 2, 4, 1])

In [29]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test.values, y_pred)
precision = precision_score(y_test.values, y_pred, average='weighted', zero_division=1)
recall = recall_score(y_test.values, y_pred, average='weighted', zero_division=1)
f1 = f1_score(y_test.values, y_pred, average='weighted', zero_division=1)

print(f"Accuracy: {accuracy.round(2)}")
print(f"Precision: {precision.round(2)}")
print(f"Recall: {recall.round(2)}")
print(f"F1: {f1.round(2)}")

print(classification_report(y_test.values, y_pred, zero_division=1))
print(confusion_matrix(y_test.values, y_pred))

Accuracy: 0.64
Precision: 0.6
Recall: 0.64
F1: 0.62
              precision    recall  f1-score   support

           1       0.74      0.84      0.79       160
           2       0.43      0.40      0.41        65
           3       0.58      0.60      0.59        50
           4       0.00      0.00      0.00        13
           5       0.33      0.10      0.15        10

    accuracy                           0.64       298
   macro avg       0.42      0.39      0.39       298
weighted avg       0.60      0.64      0.62       298

[[134  19   5   0   2]
 [ 23  26  15   1   0]
 [  9  10  30   1   0]
 [  6   5   2   0   0]
 [  8   1   0   0   1]]


In [30]:
# print the error position
print("(test, pred)")
for i in range(len(y_test)):
    if y_test.values[i] != y_pred[i]:
        print((y_test.values[i], y_pred[i]))

(test, pred)
(2, 1)
(3, 1)
(2, 3)
(2, 3)
(3, 1)
(3, 2)
(3, 1)
(4, 2)
(1, 3)
(5, 2)
(1, 2)
(2, 1)
(5, 1)
(1, 5)
(4, 1)
(3, 1)
(4, 2)
(1, 2)
(2, 1)
(3, 2)
(1, 2)
(3, 2)
(3, 1)
(3, 2)
(4, 2)
(2, 1)
(2, 3)
(1, 2)
(3, 2)
(2, 1)
(2, 1)
(5, 1)
(5, 1)
(2, 1)
(2, 1)
(1, 2)
(2, 3)
(1, 2)
(2, 1)
(5, 1)
(2, 1)
(2, 3)
(1, 2)
(4, 2)
(1, 2)
(4, 1)
(1, 2)
(2, 3)
(2, 1)
(1, 2)
(5, 1)
(1, 2)
(3, 4)
(3, 2)
(1, 3)
(2, 3)
(4, 3)
(3, 1)
(2, 3)
(2, 1)
(1, 2)
(3, 1)
(4, 1)
(2, 1)
(1, 2)
(4, 2)
(1, 2)
(2, 1)
(5, 1)
(1, 3)
(3, 1)
(4, 3)
(2, 3)
(5, 1)
(4, 1)
(3, 2)
(2, 3)
(2, 1)
(1, 5)
(3, 2)
(2, 1)
(2, 1)
(2, 1)
(2, 1)
(1, 2)
(4, 1)
(2, 3)
(5, 1)
(1, 3)
(3, 1)
(2, 1)
(2, 3)
(2, 1)
(2, 3)
(3, 2)
(3, 2)
(1, 2)
(1, 2)
(1, 2)
(1, 2)
(4, 1)
(2, 1)
(1, 3)
(2, 1)
(2, 3)
(2, 3)
(2, 4)
