In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
df = pd.read_csv('Training Dataset/training datalist.csv')
display(df.head())

ID  Sex  Age  Disease category  Narrow pitch range  Decreased volume  \
0  1202f15    2   39                 1                   1                 1   
1  0600ve0    1   69                 2                   1                 1   
2  1001o7l    2   59                 2                   1                 1   
3  1201c1t    2   47                 1                   1                 0   
4  0402jvt    1   87                 1                   0                 0   

   Fatigue  Dryness  Lumping  heartburn  ...  Onset of dysphonia   \
0        1        1        1          0  ...                    2   
1        1        1        0          0  ...                    2   
2        1        1        0          0  ...                    2   
3        1        1        1          0  ...                    3   
4        0        0        0          0  ...                    1   

   Noise at work  Occupational vocal demand  Diabetes  Hypertension  CAD  \
0              3                          1         0             0    0   
1              1                          3         0             0    0   
2              3                          4         0             0    0   
3              1                          1         0             0    0   
4              1                          4         0             1    0   

   Head and Neck Cancer  Head injury  CVA  Voice handicap index - 10  
0                     0            0    0                       22.0  
1                     0            0    1                       19.0  
2                     0            0    0                       18.0  
3                     0            0    0                       27.0  
4                     0            0    0                       16.0  

[5 rows x 28 columns]

In [27]:
# data cleaning
df['PPD'].fillna(0, inplace=True)
df.dropna(subset=['Voice handicap index - 10'], inplace=True)
# df.info()
df.reset_index(drop=True, inplace=True)

In [28]:
top_10_features = ['Age', 'Voice handicap index - 10', 'Diurnal pattern', 'Onset of dysphonia ', 'Occupational vocal demand', 'Sex', 'Noise at work', 'Drinking', 'Fatigue', 'Smoking']

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df[top_10_features]
y = df['Disease category']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

scaler = StandardScaler().fit(X_train.values)
X_train_norm = scaler.transform(X_train.values)
X_test_norm = scaler.transform(X_test.values)

In [30]:
from sklearn.svm import SVC

svc_model = SVC()
svc_model.fit(X_train_norm, y_train.values)

y_pred = svc_model.predict(X_test_norm)

In [31]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test.values, y_pred)
precision = precision_score(y_test.values, y_pred, average='weighted', zero_division=1)
recall = recall_score(y_test.values, y_pred, average='weighted', zero_division=1)
f1 = f1_score(y_test.values, y_pred, average='weighted', zero_division=1)

print(f"Accuracy: {accuracy.round(2)}")
print(f"Precision: {precision.round(2)}")
print(f"Recall: {recall.round(2)}")
print(f"F1: {f1.round(2)}")

print(classification_report(y_test.values, y_pred, zero_division=1))
print(confusion_matrix(y_test.values, y_pred))

Accuracy: 0.67
Precision: 0.69
Recall: 0.67
F1: 0.62
              precision    recall  f1-score   support

           1       0.67      0.93      0.78       153
           2       0.56      0.38      0.45        64
           3       0.77      0.56      0.65        59
           4       1.00      0.00      0.00        11
           5       1.00      0.00      0.00        11

    accuracy                           0.67       298
   macro avg       0.80      0.37      0.37       298
weighted avg       0.69      0.67      0.62       298

[[142   7   4   0   0]
 [ 34  24   6   0   0]
 [ 19   7  33   0   0]
 [  7   4   0   0   0]
 [ 10   1   0   0   0]]
